SCENARIO_HEIGHT = 10
SCENARIO_WIDTH = 10

HANDSTANDER_DMG_POINTS = 5
TUPPERWASHER_DMG_POINTS = 3
STONETHROWER_DMG_POINTS = 5

HANDSTANDER_HP_INITIAL = 100
TUPPERWASHER_HP_INITIAL = 120
STONETHROWER_HP_INITIAL = 80

WINDOWS_WIDTH = 1000
WINDOWS_HEIGHT = 1000

X_LINES = SCENARIO_WIDTH +1
Y_LINES = SCENARIO_HEIGHT +1
TEAM_1 = 'ewok'
TEAM_2 = 'trooper'

IMAGES_DIR = '/home/luciano/gitHub/automata/'
GAME_SPEED = 3