SCENARIO_HEIGHT = 10
SCENARIO_WIDTH = 10

HANDSTANDER_DMG_POINTS = 5
TUPPERWASHER_DMG_POINTS = 3
STONETHROWER_DMG_POINTS = 5

HANDSTANDER_HP_INITIAL = 100
TUPPERWASHER_HP_INITIAL = 120
STONETHROWER_HP_INITIAL = 80
