SCENARIO_HEIGHT = 10
SCENARIO_WIDTH = 10

HANDSTANDER_DMG_POINTS = 5
TUPPERWASHER_DMG_POINTS = 3
STONETHROWER_DMG_POINTS = 5

HANDSTANDER_HP_INITIAL = 100
TUPPERWASHER_HP_INITIAL = 120
STONETHROWER_HP_INITIAL = 80

windows_width = 1000
windows_height = 1000

x_lines = SCENARIO_WIDTH +1
y_lines = SCENARIO_HEIGHT +1
TEAM_1 = 'ewok'
TEAM_2 = 'trooper'
